# Generated by Django 5.1.6 on 2025-03-03 06:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TweetSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(max_length=280, verbose_name="投稿内容")),
                ("scheduled_time", models.DateTimeField(verbose_name="予定時刻")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待機中"),
                            ("posted", "投稿済み"),
                            ("failed", "失敗"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="エラーメッセージ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "ツイート予約",
                "verbose_name_plural": "ツイート予約一覧",
                "ordering": ["-scheduled_time"],
            },
        ),
    ]
