# Generated by Django 5.1.6 on 2025-03-03 07:10

import x_scheduler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x_scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweetschedule",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=x_scheduler.models.get_image_path,
                verbose_name="画像",
            ),
        ),
    ]
