# Generated by Django 5.1.7 on 2025-04-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("x_scheduler", "0004_dailypostcounter_systemsetting_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailypostcounter",
            name="max_daily_posts",
        ),
    ]
